In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
# 1 D Array
a = np.array([1,2,3,4,5])
#2D
b = np.array([[1,2,3],[4,5,6]])
# 3D Array
c = np.array([[[10,11,12],[13,14,15],[16,17,18]]])

# printing the shapes
print("1-D Array",np.ndim(a))
print('2D Array',np.ndim(b))
print('3D Array', np.ndim(c))

1-D Array 1
2D Array 2
3D Array 3

In [8]:
ar1 = np.identity(2, dtype = 'int')
print(ar1)

[[1 0]
 [0 1]]

In [10]:
np.zeros((2,5), 'int')

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [11]:
a = np.zeros((2,5,1,2))
a

array([[[[0., 0.]],

        [[0., 0.]],

        [[0., 0.]],

        [[0., 0.]],

        [[0., 0.]]],


       [[[0., 0.]],

        [[0., 0.]],

        [[0., 0.]],

        [[0., 0.]],

        [[0., 0.]]]])

In [12]:
np.full((3,5), 5)

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

In [13]:
np.random.randint(0,100, 25)

array([81, 48, 83, 37, 87, 88, 31, 20,  2, 51, 78, 52, 48, 29, 81, 23, 77,
       68, 29, 34, 79, 94,  9, 81,  5], dtype=int32)

In [14]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [15]:
np.random.randint(0,100,(2,3))

array([[92, 40, 32],
       [ 9, 91, 27]], dtype=int32)

In [18]:
np.random.randint(0,100,(2,3)).reshape(3,2)

array([[42, 80],
       [24,  8],
       [96,  8]], dtype=int32)

In [20]:
arr = np.random.randint(0,1000, 50)
# print the 1st 10 elements of the array
arr[:10]

array([501, 862, 156, 437, 649, 541, 865, 149, 231, 112], dtype=int32)

In [21]:
# print the elements from the indexes 10 - 25
arr[10:25]

array([329, 858, 470, 111, 249, 925, 196, 681, 238, 829,  44, 212, 753,
       694, 954], dtype=int32)

In [22]:
arr[22]

np.int32(753)

In [24]:
arr[-10:]

array([538, 780, 103, 852, 120, 278, 854, 911, 994, 940], dtype=int32)

In [25]:
import pandas as pd

In [28]:
# Given a sample list, tuple and a set with elements as numbers from 1 - 10. Convert each of the data types into a pandas series. Create a sepaate list of index for the series.
l = [1,2,3,4,5]
t = (1,2,3,4,5)
s = {1,2,3,4,5}
i = ['a','b','c','d','e']

s1 = pd.Series(l, index = i)
print(s1)
s2 = pd.Series(t, index = i)
print(s2)

a    1
b    2
c    3
d    4
e    5
dtype: int64
a    1
b    2
c    3
d    4
e    5
dtype: int64

In [31]:
s3 = pd.Series(list(s), index = i)
print(s3)

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [34]:
# Create a python dictinary with three key:value pairs. Keep the keys as the first names, and the respective last names as values in the dictionary. Use the dictionary to create a pandas series.
d = {'Virat':'Kohli', 'Rohit':'Sharma', 'MS':'Dhoni'} 
d

{'Virat': 'Kohli', 'Rohit': 'Sharma', 'MS': 'Dhoni'}

In [35]:
d_as_Series = pd.Series(d)
d_as_Series

Virat     Kohli
Rohit    Sharma
MS        Dhoni
dtype: object

In [36]:
series = pd.Series(range(1, 11))
# convert it to list
list = list(series)
print('list',list)

# Convert it to dictionary
dict = dict(series)
print('Dictionary',dict)

# Convert it to tuple
tuple = tuple(series)
print('Tuple',tuple)

# Convert it to Set
set = set(series)
print('Set',set)

list [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
Dictionary {0: np.int64(1), 1: np.int64(2), 2: np.int64(3), 3: np.int64(4), 4: np.int64(5), 5: np.int64(6), 6: np.int64(7), 7: np.int64(8), 8: np.int64(9), 9: np.int64(10)}
Tuple (1, 2, 3, 4, 5, 6, 7, 8, 9, 10)
Set {1, 2, 3, 4, 5, 6, 7, 8, 9, 10}

In [37]:
# Create a sample pandas series with x integer elements. Perform the following operations on the same.
sample_series = pd.Series(range(1,11))

# print the first 5 elements of the series
sample_series.head()

# print the last 5 elements of the series
sample_series.tail()

# Insert an integer value '55' at the index 5
sample_series[5] = 55

# Update the last element in the series with the value 200
sample_series[10] = 200

# Delete the 1st element from the series
sample_series = sample_series.drop(0)

In [38]:
sample_series

1       2
2       3
3       4
4       5
5      55
6       7
7       8
8       9
9      10
10    200
dtype: int64

In [44]:
200 in sample_series.values

True

In [47]:
# For the given series A and B. Perform Concatenation on the same.
series_A = pd.Series([1,2,3,4,5])
series_B = pd.Series([6,7,8,9,10])

# Concatenation
a = pd.concat([series_A,series_B], ignore_index =  True)
print('Concatenated Series', a)

Concatenated Series 0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
dtype: int64

In [50]:
# For a Given Nested List and a sample dictionary create two data frames using pandas.
List = [['AA', 'BB','CC'], ['DD','EE','FF'], ['GG','HH','II']]
Dictionary = {'Kris': ['Jordan', 12, 22], 'Memphis': ['Depay', 23, 24]}

# List into dataframe
df1 = pd.DataFrame(List, columns = ['x','y','z'])
df1

    x   y   z
0  AA  BB  CC
1  DD  EE  FF
2  GG  HH  II

In [51]:
# Dictionary into dataframe
df2 = pd.DataFrame(Dictionary)
df2

     Kris Memphis
0  Jordan   Depay
1      12      23
2      22      24

In [53]:
df1.iloc[:2, :1]

    x
0  AA
1  DD

In [54]:
# All rows after 2nd
df1.iloc[2:, :]

    x   y   z
2  GG  HH  II

In [55]:
# Create a DataFrame with Columns Name and Age. Perform the following Operations.
df = {'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva'],
      'Age': [25, 20, 30, 20, 22]}

df = pd.DataFrame(df)
df

      Name  Age
0    Alice   25
1      Bob   20
2  Charlie   30
3    David   20
4      Eva   22

In [57]:
# Write a sample code to search for the Name/Names where age is 20
df[df['Age']==20]['Name']

1      Bob
3    David
Name: Name, dtype: object

In [58]:
# Sort the dataframe in ascending order of ages
df.sort_values(by='Age',ascending=True)

      Name  Age
1      Bob   20
3    David   20
4      Eva   22
0    Alice   25
2  Charlie   30

In [59]:
# Sort the data frame in descending order of ages
df.sort_values(by='Age',ascending=False)

      Name  Age
2  Charlie   30
0    Alice   25
4      Eva   22
1      Bob   20
3    David   20

In [67]:
# Using loops in python, print all the elements within a pandas Series
sample = pd.Series([1,2,3,4,5,6,7,8,9,10])
for i in sample:
    print(i)

1
2
3
4
5
6
7
8
9
10

In [71]:
# Create a sample dataframe with columns and use python loops to print the content of the columns.
df = {'Name' : ['Aishwarya','Sulochana','Prithviraj'],'Surname':['Savanth','Savanth','Savanth']}
df = pd.DataFrame(df)

for x in df.values:
    print(x)

['Aishwarya' 'Savanth']
['Sulochana' 'Savanth']
['Prithviraj' 'Savanth']